%% coding: latin-1
%%: 实现
-module(cfg_mapsetting_cht).
-compile(export_all).
-include("cfg_mapsetting.hrl").


getRow(1)->
    #mapsettingCfg {
    id = 1,
    type = 0,
    subtype = 0,
    name = "map330",
    desc = "星月岛",
    show_name = "星月岛",
    instance_group = 0,
    difficulty = 0,
    rank = 0,
    res1 = "maps/map330_PathGrid.bytes",
    res2 = "maps/map330_MapInfo.bytes",
    useminimap = "map330",
    cam_pitch = 30,
    cam_yaw = 0,
    role_direction = 3.14,
    res3 = 1,
    dropid = 0,
    equipdropid = 0,
    copyrand = 0,
    playerEnter_MinLevel = 1,
    playerEnter_MaxLevel = 150,
    pkflag = 1,
    if_addkillvalue = 0,
    music = "map330",
    worldMapx = 9999,
    worldMapy = 9999,
    maxnum = 50,
    if_single = 0,
    daily_entercount = 0,
    daily_entercount_group = 0,
    daily_effectivecount = 0,
    enter_Conditions = 0,
    enter_Conditions_Param = 0,
    scheduleConf = [],
    parallelScheduleConf = [],
    all_time = 0,
    finish_time = 0,
    wait_time = 0,
    belongto = 0,
    need_view = 3,
    kill_thelastofus = 0,
    matching = 0,
    monster_element = [],
    drop_show = [],
    onevsone = 1000,
    dropnum = 0,
    animation = 0,
    daynight = 0,
    useVitality = 0,
    attack = 0,
    timestep = [0,0],
    day = [0,0,0],
    night = [0,0,0],
    cam_yawmove = 180,
    map_type = 0,
    buytime = 0,
    buycost = [],
    teamtype = 0,
    fuhuo = 7,
    saferegionrange = 0,
    checkpoint_information = 1,
    improvePower_open = 1,
    distortion = 1,
    guidmonsterAndgroundPosition = 0,
    auto_battle = 2,
    resurrection_times = 0,
    fuhuotype = 0
    };
getRow(2)->
    #mapsettingCfg {
    id = 2,
    type = 0,
    subtype = 0,
    name = "map333",
    desc = "阿克勒港口",
    show_name = "阿克勒港口",
    instance_group = 0,
    difficulty = 0,
    rank = 0,
    res1 = "maps/map333_PathGrid.bytes",
    res2 = "maps/map333_MapInfo.bytes",
    useminimap = "map333",
    cam_pitch = 25,
    cam_yaw = 146,
    role_direction = 3.14,
    res3 = 1,
    dropid = 0,
    equipdropid = 0,
    copyrand = 0,
    playerEnter_MinLevel = 1,
    playerEnter_MaxLevel = 150,
    pkflag = 1,
    if_addkillvalue = 0,
    music = "map522&map333",
    worldMapx = -47,
    worldMapy = 301,
    maxnum = 50,
    if_single = 0,
    daily_entercount = 0,
    daily_entercount_group = 0,
    daily_effectivecount = 0,
    enter_Conditions = 0,
    enter_Conditions_Param = 0,
    scheduleConf = [],
    parallelScheduleConf = [],
    all_time = 0,
    finish_time = 0,
    wait_time = 0,
    belongto = 0,
    need_view = 4,
    kill_thelastofus = 0,
    matching = 0,
    monster_element = [],
    drop_show = [],
    onevsone = 1001,
    dropnum = 0,
    animation = 0,
    daynight = 1,
    useVitality = 0,
    attack = 0,
    timestep = [0,0],
    day = [0,0,0],
    night = [0,0,0],
    cam_yawmove = 180,
    map_type = 0,
    buytime = 0,
    buycost = [],
    teamtype = 0,
    fuhuo = 7,
    saferegionrange = 0,
    checkpoint_information = 1,
    improvePower_open = 1,
    distortion = 1,
    guidmonsterAndgroundPosition = 0,
    worldMapHighlight = [225,149],
    auto_battle = 2,
    resurrection_times = 0,
    fuhuotype = 0
    };
getRow(3)->
    #mapsettingCfg {
    id = 3,
    type = 0,
    subtype = 0,
    name = "map331",
    desc = "阿克勒平原",
    show_name = "阿克勒平原",
    instance_group = 0,
    difficulty = 0,
    rank = 0,
    res1 = "maps/map331_PathGrid.bytes",
    res2 = "maps/map331_MapInfo.bytes",
    useminimap = "map331",
    cam_pitch = 30,
    cam_yaw = 90,
    role_direction = 4.71,
    res3 = 1,
    dropid = 0,
    equipdropid = 0,
    copyrand = 0,
    playerEnter_MinLevel = 15,
    playerEnter_MaxLevel = 150,
    pkflag = 1,
    if_addkillvalue = 0,
    music = "map331&map332",
    worldMapx = 312,
    worldMapy = 286,
    maxnum = 50,
    if_single = 0,
    daily_entercount = 0,
    daily_entercount_group = 0,
    daily_effectivecount = 0,
    enter_Conditions = 0,
    enter_Conditions_Param = 0,
    scheduleConf = [],
    parallelScheduleConf = [],
    all_time = 0,
    finish_time = 0,
    wait_time = 0,
    belongto = 0,
    need_view = 3,
    kill_thelastofus = 0,
    matching = 0,
    monster_element = [],
    drop_show = [],
    onevsone = 1003,
    dropnum = 0,
    animation = 1004,
    daynight = 1,
    useVitality = 0,
    attack = 0,
    timestep = [0,0],
    day = [0,0,0],
    night = [0,0,0],
    cam_yawmove = 180,
    map_type = 0,
    buytime = 0,
    buycost = [],
    teamtype = 0,
    fuhuo = 7,
    saferegionrange = 0,
    checkpoint_information = 1,
    improvePower_open = 1,
    distortion = 1,
    monster_collect = [{6,136,100},{6,137,100},{12,136,100},{12,137,100}],
    guidmonsterAndgroundPosition = 0,
    worldMapHighlight = [253,139],
    auto_battle = 2,
    resurrection_times = 0,
    fuhuotype = 0
    };
getRow(4)->
    #mapsettingCfg {
    id = 4,
    type = 0,
    subtype = 0,
    name = "map301",
    desc = "苍空之塔",
    show_name = "苍空之塔",
    instance_group = 0,
    difficulty = 0,
    rank = 0,
    res1 = "maps/map301_PathGrid.bytes",
    res2 = "maps/map301_MapInfo.bytes",
    useminimap = "map301",
    cam_pitch = 30,
    cam_yaw = 116,
    role_direction = 5.16,
    res3 = 1,
    dropid = 0,
    equipdropid = 0,
    copyrand = 0,
    playerEnter_MinLevel = 28,
    playerEnter_MaxLevel = 150,
    pkflag = 3,
    if_addkillvalue = 1,
    music = "map301",
    worldMapx = 416,
    worldMapy = 12,
    maxnum = 50,
    if_single = 0,
    daily_entercount = 0,
    daily_entercount_group = 0,
    daily_effectivecount = 0,
    enter_Conditions = 0,
    enter_Conditions_Param = 0,
    scheduleConf = [],
    parallelScheduleConf = [],
    all_time = 0,
    finish_time = 0,
    wait_time = 0,
    belongto = 0,
    need_view = 0,
    kill_thelastofus = 0,
    matching = 0,
    monster_element = [],
    drop_show = [],
    onevsone = 1005,
    dropnum = 0,
    animation = 1008,
    daynight = 1,
    useVitality = 0,
    attack = 0,
    timestep = [0,0],
    day = [0,0,0],
    night = [0,0,0],
    cam_yawmove = 180,
    map_type = 0,
    buytime = 0,
    buycost = [],
    teamtype = 0,
    fuhuo = 7,
    saferegionrange = 30,
    checkpoint_information = 1,
    improvePower_open = 1,
    distortion = 1,
    monster_collect = [{7,140,72},{13,140,72}],
    guidmonsterAndgroundPosition = 0,
    worldMapHighlight = [344,210],
    auto_battle = 2,
    resurrection_times = 0,
    fuhuotype = 0
    };
getRow(10170)->
    #mapsettingCfg {
        id = 10170,
        type = 2,
        subtype = 0,
        name = "map334",
        desc = "越狱II",
        show_name = "精灵故土",
        instance_group = 0,
        difficulty = 0,
        rank = 0,
        res1 = "maps/map334_PathGrid.bytes",
        res2 = "maps/map334_MapInfo.bytes",
        cam_pitch = 55,
        cam_yaw = 10,
        role_direction = 0,
        res3 = 1,
        dropid = 0,
        equipdropid = 0,
        copyrand = 0,
        playerEnter_MinLevel = 1,
        playerEnter_MaxLevel = 150,
        pkflag = 1,
        if_addkillvalue = 0,
        music = "map334",
        worldMapx = 9999,
        worldMapy = 9999,
        maxnum = 1,
        if_single = 0,
        daily_entercount = 0,
        daily_entercount_group = 0,
        daily_effectivecount = 0,
        enter_Conditions = 0,
        enter_Conditions_Param = 0,
        scheduleConf = [{5099,5099},{5099,5099}],
        parallelScheduleConf = [],
        all_time = 3600,
        finish_time = 3,
        wait_time = 120,
        belongto = 11,
        need_view = 0,
        kill_thelastofus = 0,
        matching = 0,
        monster_element = [],
        drop_show = [],
        onevsone = 1000,
        dropnum = 0,
        animation = 0,
        daynight = 1,
        useVitality = 0,
        attack = 0,
        timestep = [0,0],
        day = [0,0,0],
        night = [0,0,0],
        cam_yawmove = 180,
        map_type = 0,
        buytime = 0,
        buycost = [],
        teamtype = 0,
        fuhuo = 7,
        saferegionrange = 0,
        checkpoint_information = 1,
        improvePower_open = 0,
        distortion = 0,
        guidmonsterAndgroundPosition = 0,
        worldMapHighlight = [],
        auto_battle = 2,
        resurrection_times = 0,
        fuhuotype = 0
    };
getRow(_)->[].

getKeyList()->[
    {1},
    {2},
    {3},
    {4},
    {10170}
    ].

get1KeyList()->[
    1,
    2,
    3,
    4,
    10170
    ].

