%% coding: latin-1
%%: 实现
-module(cfg_rune_chs).
-compile(export_all).
-include("cfg_rune.hrl").
-include("logger.hrl").

getRow(103000)->
    #runeCfg {
    iD = 103000,
    name = "炽日之镜",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 0,
    quality = 3,
    property_suite_id = 1,
    icon = 9550,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103001)->
    #runeCfg {
    iD = 103001,
    name = "炽日之杯",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 1,
    quality = 3,
    property_suite_id = 1,
    icon = 9556,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103002)->
    #runeCfg {
    iD = 103002,
    name = "炽日之眼",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 2,
    quality = 3,
    property_suite_id = 1,
    icon = 9562,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103003)->
    #runeCfg {
    iD = 103003,
    name = "炽日之钥",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 3,
    quality = 3,
    property_suite_id = 1,
    icon = 9568,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103004)->
    #runeCfg {
    iD = 103004,
    name = "水晶之镜",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 0,
    quality = 3,
    property_suite_id = 2,
    icon = 9551,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103005)->
    #runeCfg {
    iD = 103005,
    name = "水晶之杯",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 1,
    quality = 3,
    property_suite_id = 2,
    icon = 9557,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103006)->
    #runeCfg {
    iD = 103006,
    name = "水晶之眼",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 2,
    quality = 3,
    property_suite_id = 2,
    icon = 9563,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103007)->
    #runeCfg {
    iD = 103007,
    name = "水晶之钥",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 3,
    quality = 3,
    property_suite_id = 2,
    icon = 9569,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103008)->
    #runeCfg {
    iD = 103008,
    name = "原界之镜",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 0,
    quality = 3,
    property_suite_id = 3,
    icon = 9552,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103009)->
    #runeCfg {
    iD = 103009,
    name = "原界之杯",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 1,
    quality = 3,
    property_suite_id = 3,
    icon = 9558,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103010)->
    #runeCfg {
    iD = 103010,
    name = "原界之眼",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 2,
    quality = 3,
    property_suite_id = 3,
    icon = 9564,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103011)->
    #runeCfg {
    iD = 103011,
    name = "原界之钥",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 3,
    quality = 3,
    property_suite_id = 3,
    icon = 9570,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103012)->
    #runeCfg {
    iD = 103012,
    name = "许愿之镜",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 0,
    quality = 3,
    property_suite_id = 4,
    icon = 9553,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103013)->
    #runeCfg {
    iD = 103013,
    name = "许愿之杯",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 1,
    quality = 3,
    property_suite_id = 4,
    icon = 9559,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103014)->
    #runeCfg {
    iD = 103014,
    name = "许愿之眼",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 2,
    quality = 3,
    property_suite_id = 4,
    icon = 9565,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103015)->
    #runeCfg {
    iD = 103015,
    name = "许愿之钥",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 3,
    quality = 3,
    property_suite_id = 4,
    icon = 9571,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103016)->
    #runeCfg {
    iD = 103016,
    name = "黄金之镜",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 0,
    quality = 3,
    property_suite_id = 5,
    icon = 9554,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103017)->
    #runeCfg {
    iD = 103017,
    name = "黄金之杯",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 1,
    quality = 3,
    property_suite_id = 5,
    icon = 9560,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103018)->
    #runeCfg {
    iD = 103018,
    name = "黄金之眼",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 2,
    quality = 3,
    property_suite_id = 5,
    icon = 9566,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103019)->
    #runeCfg {
    iD = 103019,
    name = "黄金之钥",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 3,
    quality = 3,
    property_suite_id = 5,
    icon = 9572,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103020)->
    #runeCfg {
    iD = 103020,
    name = "幻梦之镜",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 0,
    quality = 3,
    property_suite_id = 6,
    icon = 9555,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103021)->
    #runeCfg {
    iD = 103021,
    name = "幻梦之杯",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 1,
    quality = 3,
    property_suite_id = 6,
    icon = 9561,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103022)->
    #runeCfg {
    iD = 103022,
    name = "幻梦之眼",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 2,
    quality = 3,
    property_suite_id = 6,
    icon = 9567,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103023)->
    #runeCfg {
    iD = 103023,
    name = "幻梦之钥",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 3,
    quality = 3,
    property_suite_id = 6,
    icon = 9573,
    random_property_group_id = 1,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [1,2],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103024)->
    #runeCfg {
    iD = 103024,
    name = "千年之镜",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 0,
    quality = 4,
    property_suite_id = 7,
    icon = 9550,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103025)->
    #runeCfg {
    iD = 103025,
    name = "千年之杯",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 1,
    quality = 4,
    property_suite_id = 7,
    icon = 9556,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103026)->
    #runeCfg {
    iD = 103026,
    name = "千年之眼",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 2,
    quality = 4,
    property_suite_id = 7,
    icon = 9562,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103027)->
    #runeCfg {
    iD = 103027,
    name = "千年之钥",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 3,
    quality = 4,
    property_suite_id = 7,
    icon = 9568,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103028)->
    #runeCfg {
    iD = 103028,
    name = "诅咒之镜",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 0,
    quality = 4,
    property_suite_id = 8,
    icon = 9551,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103029)->
    #runeCfg {
    iD = 103029,
    name = "诅咒之杯",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 1,
    quality = 4,
    property_suite_id = 8,
    icon = 9557,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103030)->
    #runeCfg {
    iD = 103030,
    name = "诅咒之眼",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 2,
    quality = 4,
    property_suite_id = 8,
    icon = 9563,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103031)->
    #runeCfg {
    iD = 103031,
    name = "诅咒之钥",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 3,
    quality = 4,
    property_suite_id = 8,
    icon = 9569,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103032)->
    #runeCfg {
    iD = 103032,
    name = "真实之镜",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 0,
    quality = 4,
    property_suite_id = 9,
    icon = 9552,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103033)->
    #runeCfg {
    iD = 103033,
    name = "真实之杯",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 1,
    quality = 4,
    property_suite_id = 9,
    icon = 9558,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103034)->
    #runeCfg {
    iD = 103034,
    name = "真实之眼",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 2,
    quality = 4,
    property_suite_id = 9,
    icon = 9564,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103035)->
    #runeCfg {
    iD = 103035,
    name = "真实之钥",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 3,
    quality = 4,
    property_suite_id = 9,
    icon = 9570,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103036)->
    #runeCfg {
    iD = 103036,
    name = "希望之镜",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 0,
    quality = 4,
    property_suite_id = 10,
    icon = 9553,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103037)->
    #runeCfg {
    iD = 103037,
    name = "希望之杯",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 1,
    quality = 4,
    property_suite_id = 10,
    icon = 9559,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103038)->
    #runeCfg {
    iD = 103038,
    name = "希望之眼",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 2,
    quality = 4,
    property_suite_id = 10,
    icon = 9565,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103039)->
    #runeCfg {
    iD = 103039,
    name = "希望之钥",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 3,
    quality = 4,
    property_suite_id = 10,
    icon = 9571,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103040)->
    #runeCfg {
    iD = 103040,
    name = "永恒之镜",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 0,
    quality = 4,
    property_suite_id = 11,
    icon = 9554,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103041)->
    #runeCfg {
    iD = 103041,
    name = "永恒之杯",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 1,
    quality = 4,
    property_suite_id = 11,
    icon = 9560,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103042)->
    #runeCfg {
    iD = 103042,
    name = "永恒之眼",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 2,
    quality = 4,
    property_suite_id = 11,
    icon = 9566,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103043)->
    #runeCfg {
    iD = 103043,
    name = "永恒之钥",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 3,
    quality = 4,
    property_suite_id = 11,
    icon = 9572,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103044)->
    #runeCfg {
    iD = 103044,
    name = "毁灭之镜",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 0,
    quality = 4,
    property_suite_id = 12,
    icon = 9555,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103045)->
    #runeCfg {
    iD = 103045,
    name = "毁灭之杯",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 1,
    quality = 4,
    property_suite_id = 12,
    icon = 9561,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103046)->
    #runeCfg {
    iD = 103046,
    name = "毁灭之眼",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 2,
    quality = 4,
    property_suite_id = 12,
    icon = 9567,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103047)->
    #runeCfg {
    iD = 103047,
    name = "毁灭之钥",
    type = 0,
    stage = 0,
    equipLevel = 130,
    subtype = 3,
    quality = 4,
    property_suite_id = 12,
    icon = 9573,
    random_property_group_id = 2,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [3,4],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 20000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103048)->
    #runeCfg {
    iD = 103048,
    name = "炽日之镜",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 0,
    quality = 3,
    property_suite_id = 13,
    icon = 9550,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103049)->
    #runeCfg {
    iD = 103049,
    name = "炽日之杯",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 1,
    quality = 3,
    property_suite_id = 13,
    icon = 9556,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103050)->
    #runeCfg {
    iD = 103050,
    name = "炽日之眼",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 2,
    quality = 3,
    property_suite_id = 13,
    icon = 9562,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103051)->
    #runeCfg {
    iD = 103051,
    name = "炽日之钥",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 3,
    quality = 3,
    property_suite_id = 13,
    icon = 9568,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103052)->
    #runeCfg {
    iD = 103052,
    name = "水晶之镜",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 0,
    quality = 3,
    property_suite_id = 14,
    icon = 9551,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103053)->
    #runeCfg {
    iD = 103053,
    name = "水晶之杯",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 1,
    quality = 3,
    property_suite_id = 14,
    icon = 9557,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103054)->
    #runeCfg {
    iD = 103054,
    name = "水晶之眼",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 2,
    quality = 3,
    property_suite_id = 14,
    icon = 9563,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103055)->
    #runeCfg {
    iD = 103055,
    name = "水晶之钥",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 3,
    quality = 3,
    property_suite_id = 14,
    icon = 9569,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103056)->
    #runeCfg {
    iD = 103056,
    name = "原界之镜",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 0,
    quality = 3,
    property_suite_id = 15,
    icon = 9552,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103057)->
    #runeCfg {
    iD = 103057,
    name = "原界之杯",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 1,
    quality = 3,
    property_suite_id = 15,
    icon = 9558,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103058)->
    #runeCfg {
    iD = 103058,
    name = "原界之眼",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 2,
    quality = 3,
    property_suite_id = 15,
    icon = 9564,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103059)->
    #runeCfg {
    iD = 103059,
    name = "原界之钥",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 3,
    quality = 3,
    property_suite_id = 15,
    icon = 9570,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103060)->
    #runeCfg {
    iD = 103060,
    name = "许愿之镜",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 0,
    quality = 3,
    property_suite_id = 16,
    icon = 9553,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103061)->
    #runeCfg {
    iD = 103061,
    name = "许愿之杯",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 1,
    quality = 3,
    property_suite_id = 16,
    icon = 9559,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103062)->
    #runeCfg {
    iD = 103062,
    name = "许愿之眼",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 2,
    quality = 3,
    property_suite_id = 16,
    icon = 9565,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103063)->
    #runeCfg {
    iD = 103063,
    name = "许愿之钥",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 3,
    quality = 3,
    property_suite_id = 16,
    icon = 9571,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103064)->
    #runeCfg {
    iD = 103064,
    name = "黄金之镜",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 0,
    quality = 3,
    property_suite_id = 17,
    icon = 9554,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103065)->
    #runeCfg {
    iD = 103065,
    name = "黄金之杯",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 1,
    quality = 3,
    property_suite_id = 17,
    icon = 9560,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103066)->
    #runeCfg {
    iD = 103066,
    name = "黄金之眼",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 2,
    quality = 3,
    property_suite_id = 17,
    icon = 9566,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103067)->
    #runeCfg {
    iD = 103067,
    name = "黄金之钥",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 3,
    quality = 3,
    property_suite_id = 17,
    icon = 9572,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103068)->
    #runeCfg {
    iD = 103068,
    name = "幻梦之镜",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 0,
    quality = 3,
    property_suite_id = 18,
    icon = 9555,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103069)->
    #runeCfg {
    iD = 103069,
    name = "幻梦之杯",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 1,
    quality = 3,
    property_suite_id = 18,
    icon = 9561,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103070)->
    #runeCfg {
    iD = 103070,
    name = "幻梦之眼",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 2,
    quality = 3,
    property_suite_id = 18,
    icon = 9567,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103071)->
    #runeCfg {
    iD = 103071,
    name = "幻梦之钥",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 3,
    quality = 3,
    property_suite_id = 18,
    icon = 9573,
    random_property_group_id = 3,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [5,6],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103072)->
    #runeCfg {
    iD = 103072,
    name = "千年之镜",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 0,
    quality = 4,
    property_suite_id = 19,
    icon = 9550,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103073)->
    #runeCfg {
    iD = 103073,
    name = "千年之杯",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 1,
    quality = 4,
    property_suite_id = 19,
    icon = 9556,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103074)->
    #runeCfg {
    iD = 103074,
    name = "千年之眼",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 2,
    quality = 4,
    property_suite_id = 19,
    icon = 9562,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103075)->
    #runeCfg {
    iD = 103075,
    name = "千年之钥",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 3,
    quality = 4,
    property_suite_id = 19,
    icon = 9568,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103076)->
    #runeCfg {
    iD = 103076,
    name = "诅咒之镜",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 0,
    quality = 4,
    property_suite_id = 20,
    icon = 9551,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103077)->
    #runeCfg {
    iD = 103077,
    name = "诅咒之杯",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 1,
    quality = 4,
    property_suite_id = 20,
    icon = 9557,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103078)->
    #runeCfg {
    iD = 103078,
    name = "诅咒之眼",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 2,
    quality = 4,
    property_suite_id = 20,
    icon = 9563,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103079)->
    #runeCfg {
    iD = 103079,
    name = "诅咒之钥",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 3,
    quality = 4,
    property_suite_id = 20,
    icon = 9569,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103080)->
    #runeCfg {
    iD = 103080,
    name = "真实之镜",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 0,
    quality = 4,
    property_suite_id = 21,
    icon = 9552,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103081)->
    #runeCfg {
    iD = 103081,
    name = "真实之杯",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 1,
    quality = 4,
    property_suite_id = 21,
    icon = 9558,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103082)->
    #runeCfg {
    iD = 103082,
    name = "真实之眼",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 2,
    quality = 4,
    property_suite_id = 21,
    icon = 9564,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103083)->
    #runeCfg {
    iD = 103083,
    name = "真实之钥",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 3,
    quality = 4,
    property_suite_id = 21,
    icon = 9570,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103084)->
    #runeCfg {
    iD = 103084,
    name = "希望之镜",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 0,
    quality = 4,
    property_suite_id = 22,
    icon = 9553,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103085)->
    #runeCfg {
    iD = 103085,
    name = "希望之杯",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 1,
    quality = 4,
    property_suite_id = 22,
    icon = 9559,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103086)->
    #runeCfg {
    iD = 103086,
    name = "希望之眼",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 2,
    quality = 4,
    property_suite_id = 22,
    icon = 9565,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103087)->
    #runeCfg {
    iD = 103087,
    name = "希望之钥",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 3,
    quality = 4,
    property_suite_id = 22,
    icon = 9571,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103088)->
    #runeCfg {
    iD = 103088,
    name = "永恒之镜",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 0,
    quality = 4,
    property_suite_id = 23,
    icon = 9554,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103089)->
    #runeCfg {
    iD = 103089,
    name = "永恒之杯",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 1,
    quality = 4,
    property_suite_id = 23,
    icon = 9560,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103090)->
    #runeCfg {
    iD = 103090,
    name = "永恒之眼",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 2,
    quality = 4,
    property_suite_id = 23,
    icon = 9566,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103091)->
    #runeCfg {
    iD = 103091,
    name = "永恒之钥",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 3,
    quality = 4,
    property_suite_id = 23,
    icon = 9572,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103092)->
    #runeCfg {
    iD = 103092,
    name = "毁灭之镜",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 0,
    quality = 4,
    property_suite_id = 24,
    icon = 9555,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103093)->
    #runeCfg {
    iD = 103093,
    name = "毁灭之杯",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 1,
    quality = 4,
    property_suite_id = 24,
    icon = 9561,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103094)->
    #runeCfg {
    iD = 103094,
    name = "毁灭之眼",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 2,
    quality = 4,
    property_suite_id = 24,
    icon = 9567,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103095)->
    #runeCfg {
    iD = 103095,
    name = "毁灭之钥",
    type = 0,
    stage = 0,
    equipLevel = 170,
    subtype = 3,
    quality = 4,
    property_suite_id = 24,
    icon = 9573,
    random_property_group_id = 4,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [7,8],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 30000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103096)->
    #runeCfg {
    iD = 103096,
    name = "炽日之镜",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 0,
    quality = 3,
    property_suite_id = 25,
    icon = 9550,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103097)->
    #runeCfg {
    iD = 103097,
    name = "炽日之杯",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 1,
    quality = 3,
    property_suite_id = 25,
    icon = 9556,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103098)->
    #runeCfg {
    iD = 103098,
    name = "炽日之眼",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 2,
    quality = 3,
    property_suite_id = 25,
    icon = 9562,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103099)->
    #runeCfg {
    iD = 103099,
    name = "炽日之钥",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 3,
    quality = 3,
    property_suite_id = 25,
    icon = 9568,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103100)->
    #runeCfg {
    iD = 103100,
    name = "水晶之镜",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 0,
    quality = 3,
    property_suite_id = 26,
    icon = 9551,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103101)->
    #runeCfg {
    iD = 103101,
    name = "水晶之杯",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 1,
    quality = 3,
    property_suite_id = 26,
    icon = 9557,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103102)->
    #runeCfg {
    iD = 103102,
    name = "水晶之眼",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 2,
    quality = 3,
    property_suite_id = 26,
    icon = 9563,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103103)->
    #runeCfg {
    iD = 103103,
    name = "水晶之钥",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 3,
    quality = 3,
    property_suite_id = 26,
    icon = 9569,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103104)->
    #runeCfg {
    iD = 103104,
    name = "原界之镜",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 0,
    quality = 3,
    property_suite_id = 27,
    icon = 9552,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103105)->
    #runeCfg {
    iD = 103105,
    name = "原界之杯",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 1,
    quality = 3,
    property_suite_id = 27,
    icon = 9558,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103106)->
    #runeCfg {
    iD = 103106,
    name = "原界之眼",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 2,
    quality = 3,
    property_suite_id = 27,
    icon = 9564,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103107)->
    #runeCfg {
    iD = 103107,
    name = "原界之钥",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 3,
    quality = 3,
    property_suite_id = 27,
    icon = 9570,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103108)->
    #runeCfg {
    iD = 103108,
    name = "许愿之镜",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 0,
    quality = 3,
    property_suite_id = 28,
    icon = 9553,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103109)->
    #runeCfg {
    iD = 103109,
    name = "许愿之杯",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 1,
    quality = 3,
    property_suite_id = 28,
    icon = 9559,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103110)->
    #runeCfg {
    iD = 103110,
    name = "许愿之眼",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 2,
    quality = 3,
    property_suite_id = 28,
    icon = 9565,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103111)->
    #runeCfg {
    iD = 103111,
    name = "许愿之钥",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 3,
    quality = 3,
    property_suite_id = 28,
    icon = 9571,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103112)->
    #runeCfg {
    iD = 103112,
    name = "黄金之镜",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 0,
    quality = 3,
    property_suite_id = 29,
    icon = 9554,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103113)->
    #runeCfg {
    iD = 103113,
    name = "黄金之杯",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 1,
    quality = 3,
    property_suite_id = 29,
    icon = 9560,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103114)->
    #runeCfg {
    iD = 103114,
    name = "黄金之眼",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 2,
    quality = 3,
    property_suite_id = 29,
    icon = 9566,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103115)->
    #runeCfg {
    iD = 103115,
    name = "黄金之钥",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 3,
    quality = 3,
    property_suite_id = 29,
    icon = 9572,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103116)->
    #runeCfg {
    iD = 103116,
    name = "幻梦之镜",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 0,
    quality = 3,
    property_suite_id = 30,
    icon = 9555,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103117)->
    #runeCfg {
    iD = 103117,
    name = "幻梦之杯",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 1,
    quality = 3,
    property_suite_id = 30,
    icon = 9561,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103118)->
    #runeCfg {
    iD = 103118,
    name = "幻梦之眼",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 2,
    quality = 3,
    property_suite_id = 30,
    icon = 9567,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103119)->
    #runeCfg {
    iD = 103119,
    name = "幻梦之钥",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 3,
    quality = 3,
    property_suite_id = 30,
    icon = 9573,
    random_property_group_id = 5,
    min_num = 1,
    max_num = 3,
    skillenha_group_id = [9,10],
    skillenha_min_num = 2,
    skillenha_max_num = 2,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103120)->
    #runeCfg {
    iD = 103120,
    name = "千年之镜",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 0,
    quality = 4,
    property_suite_id = 31,
    icon = 9550,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103121)->
    #runeCfg {
    iD = 103121,
    name = "千年之杯",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 1,
    quality = 4,
    property_suite_id = 31,
    icon = 9556,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103122)->
    #runeCfg {
    iD = 103122,
    name = "千年之眼",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 2,
    quality = 4,
    property_suite_id = 31,
    icon = 9562,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103123)->
    #runeCfg {
    iD = 103123,
    name = "千年之钥",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 3,
    quality = 4,
    property_suite_id = 31,
    icon = 9568,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103124)->
    #runeCfg {
    iD = 103124,
    name = "诅咒之镜",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 0,
    quality = 4,
    property_suite_id = 32,
    icon = 9551,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103125)->
    #runeCfg {
    iD = 103125,
    name = "诅咒之杯",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 1,
    quality = 4,
    property_suite_id = 32,
    icon = 9557,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103126)->
    #runeCfg {
    iD = 103126,
    name = "诅咒之眼",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 2,
    quality = 4,
    property_suite_id = 32,
    icon = 9563,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103127)->
    #runeCfg {
    iD = 103127,
    name = "诅咒之钥",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 3,
    quality = 4,
    property_suite_id = 32,
    icon = 9569,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103128)->
    #runeCfg {
    iD = 103128,
    name = "真实之镜",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 0,
    quality = 4,
    property_suite_id = 33,
    icon = 9552,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103129)->
    #runeCfg {
    iD = 103129,
    name = "真实之杯",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 1,
    quality = 4,
    property_suite_id = 33,
    icon = 9558,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103130)->
    #runeCfg {
    iD = 103130,
    name = "真实之眼",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 2,
    quality = 4,
    property_suite_id = 33,
    icon = 9564,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103131)->
    #runeCfg {
    iD = 103131,
    name = "真实之钥",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 3,
    quality = 4,
    property_suite_id = 33,
    icon = 9570,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103132)->
    #runeCfg {
    iD = 103132,
    name = "希望之镜",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 0,
    quality = 4,
    property_suite_id = 34,
    icon = 9553,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103133)->
    #runeCfg {
    iD = 103133,
    name = "希望之杯",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 1,
    quality = 4,
    property_suite_id = 34,
    icon = 9559,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103134)->
    #runeCfg {
    iD = 103134,
    name = "希望之眼",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 2,
    quality = 4,
    property_suite_id = 34,
    icon = 9565,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103135)->
    #runeCfg {
    iD = 103135,
    name = "希望之钥",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 3,
    quality = 4,
    property_suite_id = 34,
    icon = 9571,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103136)->
    #runeCfg {
    iD = 103136,
    name = "永恒之镜",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 0,
    quality = 4,
    property_suite_id = 35,
    icon = 9554,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103137)->
    #runeCfg {
    iD = 103137,
    name = "永恒之杯",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 1,
    quality = 4,
    property_suite_id = 35,
    icon = 9560,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103138)->
    #runeCfg {
    iD = 103138,
    name = "永恒之眼",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 2,
    quality = 4,
    property_suite_id = 35,
    icon = 9566,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(103139)->
    #runeCfg {
    iD = 103139,
    name = "永恒之钥",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 3,
    quality = 4,
    property_suite_id = 35,
    icon = 9572,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.3,
    usefulLife = 0,
    inbind = 1
    };
getRow(103140)->
    #runeCfg {
    iD = 103140,
    name = "毁灭之镜",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 0,
    quality = 4,
    property_suite_id = 36,
    icon = 9555,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.4,
    usefulLife = 0,
    inbind = 1
    };
getRow(103141)->
    #runeCfg {
    iD = 103141,
    name = "毁灭之杯",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 1,
    quality = 4,
    property_suite_id = 36,
    icon = 9561,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.5,
    usefulLife = 0,
    inbind = 1
    };
getRow(103142)->
    #runeCfg {
    iD = 103142,
    name = "毁灭之眼",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 2,
    quality = 4,
    property_suite_id = 36,
    icon = 9567,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.1,
    usefulLife = 0,
    inbind = 1
    };
getRow(103143)->
    #runeCfg {
    iD = 103143,
    name = "毁灭之钥",
    type = 0,
    stage = 0,
    equipLevel = 210,
    subtype = 3,
    quality = 4,
    property_suite_id = 36,
    icon = 9573,
    random_property_group_id = 6,
    min_num = 2,
    max_num = 4,
    skillenha_group_id = [11,12],
    skillenha_min_num = 2,
    skillenha_max_num = 3,
    trans_max_num = 5,
    rune_price = 40000,
    based_property_group_id = 0,
    level_up_group_id = 0,
    exp_group_id = 0,
    smeltcost = 0,
    need_equipit = 0,
    battlepower_add = 1.2,
    usefulLife = 0,
    inbind = 1
    };
getRow(_)->[].

getKeyList()->[
    {103000},
    {103001},
    {103002},
    {103003},
    {103004},
    {103005},
    {103006},
    {103007},
    {103008},
    {103009},
    {103010},
    {103011},
    {103012},
    {103013},
    {103014},
    {103015},
    {103016},
    {103017},
    {103018},
    {103019},
    {103020},
    {103021},
    {103022},
    {103023},
    {103024},
    {103025},
    {103026},
    {103027},
    {103028},
    {103029},
    {103030},
    {103031},
    {103032},
    {103033},
    {103034},
    {103035},
    {103036},
    {103037},
    {103038},
    {103039},
    {103040},
    {103041},
    {103042},
    {103043},
    {103044},
    {103045},
    {103046},
    {103047},
    {103048},
    {103049},
    {103050},
    {103051},
    {103052},
    {103053},
    {103054},
    {103055},
    {103056},
    {103057},
    {103058},
    {103059},
    {103060},
    {103061},
    {103062},
    {103063},
    {103064},
    {103065},
    {103066},
    {103067},
    {103068},
    {103069},
    {103070},
    {103071},
    {103072},
    {103073},
    {103074},
    {103075},
    {103076},
    {103077},
    {103078},
    {103079},
    {103080},
    {103081},
    {103082},
    {103083},
    {103084},
    {103085},
    {103086},
    {103087},
    {103088},
    {103089},
    {103090},
    {103091},
    {103092},
    {103093},
    {103094},
    {103095},
    {103096},
    {103097},
    {103098},
    {103099},
    {103100},
    {103101},
    {103102},
    {103103},
    {103104},
    {103105},
    {103106},
    {103107},
    {103108},
    {103109},
    {103110},
    {103111},
    {103112},
    {103113},
    {103114},
    {103115},
    {103116},
    {103117},
    {103118},
    {103119},
    {103120},
    {103121},
    {103122},
    {103123},
    {103124},
    {103125},
    {103126},
    {103127},
    {103128},
    {103129},
    {103130},
    {103131},
    {103132},
    {103133},
    {103134},
    {103135},
    {103136},
    {103137},
    {103138},
    {103139},
    {103140},
    {103141},
    {103142},
    {103143}
    ].

get1KeyList()->[
    103000,
    103001,
    103002,
    103003,
    103004,
    103005,
    103006,
    103007,
    103008,
    103009,
    103010,
    103011,
    103012,
    103013,
    103014,
    103015,
    103016,
    103017,
    103018,
    103019,
    103020,
    103021,
    103022,
    103023,
    103024,
    103025,
    103026,
    103027,
    103028,
    103029,
    103030,
    103031,
    103032,
    103033,
    103034,
    103035,
    103036,
    103037,
    103038,
    103039,
    103040,
    103041,
    103042,
    103043,
    103044,
    103045,
    103046,
    103047,
    103048,
    103049,
    103050,
    103051,
    103052,
    103053,
    103054,
    103055,
    103056,
    103057,
    103058,
    103059,
    103060,
    103061,
    103062,
    103063,
    103064,
    103065,
    103066,
    103067,
    103068,
    103069,
    103070,
    103071,
    103072,
    103073,
    103074,
    103075,
    103076,
    103077,
    103078,
    103079,
    103080,
    103081,
    103082,
    103083,
    103084,
    103085,
    103086,
    103087,
    103088,
    103089,
    103090,
    103091,
    103092,
    103093,
    103094,
    103095,
    103096,
    103097,
    103098,
    103099,
    103100,
    103101,
    103102,
    103103,
    103104,
    103105,
    103106,
    103107,
    103108,
    103109,
    103110,
    103111,
    103112,
    103113,
    103114,
    103115,
    103116,
    103117,
    103118,
    103119,
    103120,
    103121,
    103122,
    103123,
    103124,
    103125,
    103126,
    103127,
    103128,
    103129,
    103130,
    103131,
    103132,
    103133,
    103134,
    103135,
    103136,
    103137,
    103138,
    103139,
    103140,
    103141,
    103142,
    103143
    ].

